version: '2'

services:
  pycharm_installed_in_box:
    build:
      context: .
      args:
        build_username: ${USER}
        build_uid: ${DOCKER_BUILD_UID}
    container_name: project_pycharm_installed
    network_mode: "host"
    command: /opt/pycharm-community-2019.1.1/bin/pycharm.sh
    environment:
      - DISPLAY
      - XAUTHORITY=${XAUTH_DOCKER}
      - QT_X11_NO_MITSHM=1
      - Dataset_Dir=/Datasets
      - Src_Dir=/app
      - Scratch_Dir=/scratch
    volumes:
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ~/Datasets:/Datasets:ro
      - ~/Project_Foo/src:/app:rw
      - ~/Job_123_Scratch:/scratch:rw
      - ~/opt/:/opt/
